version: "3.9"

services:
  cloudflare-ddns:
    build: .
    container_name: aktechno-ddns
    restart: unless-stopped
    environment:
      - CF_API_TOKEN=${CF_API_TOKEN}
      - CF_ZONE=${CF_ZONE}
      - CF_RECORD=${CF_RECORD}
      - CF_TTL=${CF_TTL:-1}
      - CF_PROXY=${CF_PROXY:-false}
      - TZ=Europe/London
    networks:
      - pilot-network

networks:
  pilot-network:
    external: true
